<a href="https://colab.research.google.com/github/joynaomi81/Tensorflow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
import tensorflow as tf

In [ ]:
# How to create a variable
var = tf.Variable(0)

In [ ]:
# how to create a constant
const = tf.constant(1)

In [ ]:
# add new value
new_value = tf.add(var, const)

In [ ]:
# how to change the value of a variable
update_value = var.assign(var, new_value)
print(new_value)

Tensor("Add_1:0", shape=(), dtype=int32)


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

In [ ]:
init = tf.global_variables_initializer()

In [ ]:
sess = tf.Session()

In [ ]:
sess.run(init) # initialize variable

In [ ]:
print(sess.run(var))

0


In [ ]:
for _ in range(5):
    sess.run(update_value)
    print(sess.run(var))

0
0
0
0
0


In [ ]:
 hello = tf.constant('Hello, TensorFlow!') # string operation

In [ ]:
print(sess.run(hello))

b'Hello, TensorFlow!'


In [ ]:
# placeholder
# how to create a placeholder
a = tf.placeholder(tf.float32)

In [ ]:
b=a*3

In [ ]:
# feeding a placeholder with scalar
result = sess.run(b, feed_dict={a:5})
print(result)

15.0


In [ ]:
#feeding a placeholder with vector of rank 1
result = sess.run(b, feed_dict={a:[1,2,3]})
print(result)


[3. 6. 9.]


In [ ]:
 #feeding a placeholder with multidimensional vector
 dictionary={a:[[[1,2,5], [3,4,9], [5,6,7], [8,9,5], [4,6,8], [9,8,7], [7,9,8]]]}
 result = sess.run(b,feed_dict=dictionary)
 print(result)

[[[ 3.  6. 15.]
  [ 9. 12. 27.]
  [15. 18. 21.]
  [24. 27. 15.]
  [12. 18. 24.]
  [27. 24. 21.]
  [21. 27. 24.]]]


In [ ]:
#close session
sess.close()

In [ ]:
# create a session
with tf.Session() as sess:
    result=sess.run(hello)
    print(result)

b'Hello, TensorFlow!'
